description: speech_lm

target:
  name: msrresrchvc # 80G A100  
  # name: msroctovc # 40G A100
  service: sing
  workspace_name: Workspace_NLC # 

environment:
  image:  worstchan/slam-omni:v0  # unset CUDA_VISIBLE_DEVICES
  # setup:
  #   - pip install timm
    
code:
  local_dir: /home/v-wenxichen/SLAM-LLM/ #$CONFIG_DIR/../

storage:
  blob_valle:
    storage_account_name: valle
    container_name: users
    mount_dir: /valleblob
    mount_options: ["-o", "attr_timeout=240"]

# amlt run ./examples/s2s/scripts/job/train_slam_omni.yaml 666 -y

search:
  job_template:
    name: slam-omni_v0
    # sku: 4x32G8-V100-IB
    sku: 1x80G4-A100 
    # sku: 1x40G8-A100 
    # sku: 80G8-H100-NvLink
    # sku: 3xND96rs_v4 # 40 8 a100
    sla_tier: Premium
    priority: high
    process_count_per_node: 1
    identity: managed
    command:
      #- conda init
      # - source activate py36
      # - export model_path=/valleblob/vzongyili/cv/model/tats/vqgan/vqgan_ucf101_baseline_g{gpus}_b{batch_size}_wandb
      # - bash ./examples/s2s/scripts/finetune_s2s.sh {gpus} #{batch_size} $$model_path
      # - bash ./examples/s2s/scripts/finetune_s2s_fp16.sh {gpus} #{batch_size} $$model_path
      # - bash ./examples/s2s/scripts/finetune_s2s_embed_only.sh {gpus}
      - bash ./examples/s2s/scripts/finetune_s2s_embed_only.sh {gpus}
      # - bash test.sh {gpus}
      # - sleep 3h
      - sleep infinity
    submit_args:
      env:
        NCCL_DEBUG: INFO
        MKL_NUM_THREADS: 1
        OMP_NUM_THREADS: 1
        MKL_SERVICE_FORCE_INTEL: 1
        AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/90b9bfec-2ded-494a-9ccc-b584c55f454f/resourceGroups/conversationhub/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nlc_intern"
  type: grid
  max_trials: 500
  
  params:
    - name: gpus
      spec: discrete
      values: [4]
      # values: [8]
 